{{- if .Values.monitoring.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.monitoring.path }}
      interval: 30s
{{- end }}
